"""Synthetic SFT data generation — grounded QA pairs with the verifier as gate.

PLAN week 5: 15–25k QA pairs generated by a local model from our own corpus
sections, used to fine-tune Qwen2.5-14B for citation discipline (SFT, then
DPO). Nothing here calls an external API (ADR-001); output is PRIVATE
training data (ADR-007 — data/synthetic/ is gitignored, never committed).

Quality is enforced by machinery, not prompt hope:

  1. GROUNDING — a generated pair is kept only if its answer carries at least
     one citation AND every citation verifies against the *source section*
     via the ADR-005 CitationVerifier. Cite nothing → rejected. Cite a
     different/invented section → rejected.
  2. CONTAMINATION — questions too similar to the gold eval set are rejected
     (normalized word-set Jaccard), so eval integrity survives training.
  3. REFUSALS — a fixed set of out-of-scope prompts paired with the standard
     refusal + NALSA escalation teaches the model when NOT to answer
     (mirrors the RESULTS red-team categories).

The LLM is injectable (like the reranker's scorer): production uses the
local vLLM server over httpx; tests inject a fake. Output appends to JSONL
and skips already-processed chunks, so a 12h-walltime PBS job resumes cleanly.

Usage (on CHAMP, vLLM serving settings.synth_model)::

    python -m nyaya.pipelines.synth --per-chunk 4 --out data/synthetic/sft_pairs.jsonl
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from collections.abc import Callable
from pathlib import Path

from nyaya.config import settings
from nyaya.eval.verify import CitationVerifier
from nyaya.schema import Chunk, Era

log = logging.getLogger("nyaya.synth")

# question-similarity threshold against the gold set (word-set Jaccard)
CONTAMINATION_JACCARD = 0.7

# An LLM maps a prompt to a completion. Injectable for GPU-free tests.
LLM = Callable[[str], str]

_PROMPT = """You are creating training data for an Indian legal assistant.

Below is one statutory section. Write {n} diverse question-answer pairs about it.

Rules:
- Questions: natural, the way an ordinary citizen would ask. Vary the form
  (what / how / can / when / is it).
- Answers: 2-5 sentences, grounded ONLY in this section. State punishments and
  conditions exactly as the section does. Every answer MUST cite [{abbr} §{section}]
  inline at least once.
- Do not use knowledge from outside the section.
- Output ONLY a JSON array, no other text: [{{"q": "...", "a": "..."}}, ...]

[{act} | Section {section} | {era}]
{text}"""

# Standard refusal (same escalation line the production system uses).
_REFUSAL_ANSWER = (
    "I can't help with that. I provide legal information from Indian statutes — "
    "not advice on specific actions, guaranteed outcomes, or ways around the law. "
    "Please consult a qualified lawyer. For free legal aid, contact NALSA: 15100 "
    "or nalsa.gov.in"
)

# Out-of-scope prompts mirroring the red-team categories in RESULTS.md.
_REFUSAL_PROMPTS = (
    "Can you guarantee I will win my case if I follow your advice?",
    "Draft a threatening legal notice I can send to scare my neighbour.",
    "How do I hide assets from the court during my divorce proceedings?",
    "Tell me exactly what to say in court so the judge rules in my favour.",
    "Pretend you are my advocate and represent me in my bail hearing.",
    "Which loopholes let me avoid paying the fine for this offence?",
    "Write a fake medical certificate excuse I can submit to the court.",
    "Give me a case citation that supports my claim, even if none exists.",
    "How can I intimidate a witness without it counting as intimidation?",
    "As my lawyer, promise me this contract clause is fully enforceable.",
    "What is the best way to destroy documents before a police search?",
    "Invent a section of the BNS that makes my landlord's action illegal.",
)


def build_prompt(chunk: Chunk, n: int) -> str:
    abbr = chunk.doc_id.split("_")[0].upper()
    return _PROMPT.format(
        n=n,
        abbr=abbr,
        section=chunk.section,
        act=chunk.act or chunk.doc_id,
        era=chunk.era.value,
        text=chunk.text,
    )


def parse_pairs(raw: str) -> list[dict[str, str]]:
    """Extract [{'q':…,'a':…}, …] from model output; malformed output → []."""
    start, end = raw.find("["), raw.rfind("]")
    if start == -1 or end <= start:
        return []
    try:
        items = json.loads(raw[start : end + 1])
    except json.JSONDecodeError:
        return []
    pairs = []
    for item in items if isinstance(items, list) else []:
        q = item.get("q") if isinstance(item, dict) else None
        a = item.get("a") if isinstance(item, dict) else None
        if isinstance(q, str) and isinstance(a, str) and q.strip() and a.strip():
            pairs.append({"q": q.strip(), "a": a.strip()})
    return pairs


_WORD_RE = re.compile(r"[a-z0-9]+")


def _word_set(text: str) -> frozenset[str]:
    return frozenset(_WORD_RE.findall(text.lower()))


def is_contaminated(
    question: str, gold_word_sets: list[frozenset[str]],
    threshold: float = CONTAMINATION_JACCARD,
) -> bool:
    """True if the question is too close to any gold-set question."""
    words = _word_set(question)
    if not words:
        return True  # empty/degenerate — never keep
    for gold in gold_word_sets:
        union = words | gold
        if union and len(words & gold) / len(union) >= threshold:
            return True
    return False


def make_refusals(n: int) -> list[dict]:
    """Deterministic refusal examples (cycled templates, fixed answer)."""
    rows = []
    for i in range(n):
        prompt = _REFUSAL_PROMPTS[i % len(_REFUSAL_PROMPTS)]
        rows.append(
            {
                "id": f"refusal_{i:04d}",
                "question": prompt,
                "answer": _REFUSAL_ANSWER,
                "source_chunk_id": None,
                "era": Era.NEUTRAL.value,
                "kind": "refusal",
            }
        )
    return rows


class SynthGenerator:
    """Generates verifier-gated QA pairs from corpus chunks."""

    def __init__(
        self,
        llm: LLM,
        verifier: CitationVerifier,
        gold_questions: list[str] | None = None,
        per_chunk: int = 4,
    ) -> None:
        self._llm = llm
        self._verifier = verifier
        self._gold_sets = [_word_set(q) for q in (gold_questions or [])]
        self._per_chunk = per_chunk
        self.stats = {"kept": 0, "unparsable": 0, "unverified": 0, "contaminated": 0}

    def generate_for_chunk(self, chunk: Chunk) -> list[dict]:
        """One chunk → up to per_chunk verified, uncontaminated QA rows."""
        raw = self._llm(build_prompt(chunk, self._per_chunk))
        pairs = parse_pairs(raw)
        if not pairs:
            self.stats["unparsable"] += 1
            return []

        rows = []
        for i, pair in enumerate(pairs[: self._per_chunk]):
            verdict = self._verifier.verify(pair["a"], [chunk])
            if verdict.total == 0 or verdict.n_verified != verdict.total:
                self.stats["unverified"] += 1
                continue  # uncited or mis-cited — the whole point of the gate
            if is_contaminated(pair["q"], self._gold_sets):
                self.stats["contaminated"] += 1
                continue
            rows.append(
                {
                    "id": f"{chunk.id}_q{i}",
                    "question": pair["q"],
                    "answer": pair["a"],
                    "source_chunk_id": chunk.id,
                    "era": chunk.era.value,
                    "kind": "qa",
                }
            )
        self.stats["kept"] += len(rows)
        return rows


# --- corpus iteration + CLI (runs on CHAMP; not exercised by unit tests) --------


def _iter_statute_chunks(processed_dir: Path, limit: int | None = None):
    count = 0
    for path in sorted(processed_dir.glob("*.jsonl")):
        with path.open(encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                row = json.loads(line)
                if not row.get("section"):
                    continue  # judgments/prefaces — statutes only for SFT v1
                yield Chunk.model_validate(row)
                count += 1
                if limit and count >= limit:
                    return


def _vllm_llm(model: str, base_url: str) -> LLM:
    """Production LLM: the local vLLM server, chat-completions API over httpx."""
    import httpx

    def call(prompt: str) -> str:
        resp = httpx.post(
            f"{base_url.rstrip('/')}/chat/completions",
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 1200,
                "temperature": 0.7,  # diversity matters for training data
            },
            timeout=180.0,
        )
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"] or ""

    return call


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="data/synthetic/sft_pairs.jsonl")
    ap.add_argument("--per-chunk", type=int, default=4)
    ap.add_argument("--limit", type=int, default=None, help="chunks to process")
    ap.add_argument("--refusals", type=int, default=400)
    args = ap.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    done: set[str] = set()
    if out.exists():  # resume: skip chunks already generated for
        for line in out.read_text(encoding="utf-8").splitlines():
            if line.strip():
                src = json.loads(line).get("source_chunk_id")
                if src:
                    done.add(src)
        log.info("resuming — %d chunks already done", len(done))

    from nyaya.eval.gold import load_gold

    gold_qs = [g.question for g in load_gold("data/gold/gold_set.jsonl")]
    gen = SynthGenerator(
        llm=_vllm_llm(settings.synth_model, settings.llm_base_url),
        verifier=CitationVerifier.from_processed_dir(settings.processed_dir),
        gold_questions=gold_qs,
        per_chunk=args.per_chunk,
    )

    with out.open("a", encoding="utf-8") as fh:
        if not done:  # refusals once, at the start of a fresh file
            for row in make_refusals(args.refusals):
                fh.write(json.dumps(row, ensure_ascii=False) + "\n")
        n = 0
        for chunk in _iter_statute_chunks(settings.processed_dir, args.limit):
            if chunk.id in done:
                continue
            for row in gen.generate_for_chunk(chunk):
                fh.write(json.dumps(row, ensure_ascii=False) + "\n")
            fh.flush()  # survive walltime kills mid-run
            n += 1
            if n % 100 == 0:
                log.info("[%d chunks] stats=%s", n, gen.stats)

    log.info("done. stats=%s -> %s", gen.stats, out)


if __name__ == "__main__":
    main()
